version: '2'

services:
    backend:
        build: .
        ports:
            - 8000:8000
            - 9229:9229 #debugger port
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            PORT: 8000
            DATABASE_URL: postgres://postgres:postgres@database/superstack_dev
        command: npm run start:docker
        depends_on:
            - database

    database:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: superstack_dev
            POSTGRES_HOST_AUTH_METHOD: trust
